In [1]:
import pandas as pd
from pathlib import Path

base_path = Path("../app/data/datasets")

In [32]:
df = pd.read_csv(base_path / "product_reference.csv", decimal=",")
df

,gtin,inn,product_name,product_short_name,tnved,tnved10,brand,country,volume
0,8C414C7757D587886C10DB0CCEA641A2,D0B1FE981FCC19F934C3FFD91690430F,68F60FA530914522B26E25F262EBC6D6,9199AB529CF62D4BDB7E8B1D7459001D,6D2580183CEF6C8AF1CC72E1C6E6FBC4,58A4B52373651DA4292AD5725D388F8A,D2D1641B196DA5477D40C0907FD5F1DA,NaN,10
1,3D8C701836C4C0A5B33D57522A7EDBAB,9B0AFDA27FCCB188768FA9B611183387,670017E2D871B8962E5456CA71F6A1D1,9199AB529CF62D4BDB7E8B1D7459001D,6D2580183CEF6C8AF1CC72E1C6E6FBC4,58A4B52373651DA4292AD5725D388F8A,670017E2D871B8962E5456CA71F6A1D1,NaN,10
2,B1308C75C38993B0EEA22C8FE2899C2A,86CAE1EAD8AF200ED46453FD18FA1A04,97181A85E3400C38AB223F17A5DCCFCC,9199AB529CF62D4BDB7E8B1D7459001D,6D2580183CEF6C8AF1CC72E1C6E6FBC4,FAEA36DABA0E46CD081A7FA49DAD8FE0,ABB51261177B26E23AC2DE0F0508D6AB,NaN,100
3,1D71E57CA201A8ACEADBAA8D6E7039DE,86CAE1EAD8AF200ED46453FD18FA1A04,EA5CEDF8FA0F5BEBD2F047151B2DBE86,B8AF2335E04E7BAD5168D9B39FABAC21,6D2580183CEF6C8AF1CC72E1C6E6FBC4,FAEA36DABA0E46CD081A7FA49DAD8FE0,EDFFD44E0EC18764685E952553560EEF,NaN,100
4,5DEF4AA62907D322F85FA88839F00E8F,86CAE1EAD8AF200ED46453FD18FA1A04,75AF532015CFA92F71FF54ADEDB9BEA3,9199AB529CF62D4BDB7E8B1D7459001D,6D2580183CEF6C8AF1CC72E1C6E6FBC4,FAEA36DABA0E46CD081A7FA49DAD8FE0,75AF532015CFA92F71FF54ADEDB9BEA3,NaN,50
...,...,...,...,...,...,...,...,...,...
342731,9205239C92C9E581328496DB794F60EC,8F599665A672F2CB6D29C23D4DAC7B9D,F8EE293A2AC51173AF97BE12876D6500,9199AB529CF62D4BDB7E8B1D7459001D,6D2580183CEF6C8AF1CC72E1C6E6FBC4,FAEA36DABA0E46CD081A7FA49DAD8FE0,2B4A0053B03542072C3C13C9A3EC33E1,NaN,100
342732,AD775CC9CB0F39F9A5541C2CCE12E4E6,3B5BEA39AF78664AEA44752371845804,EE747123845C7B4F4EA96B3626538577,B8AF2335E04E7BAD5168D9B39FABAC21,6D2580183CEF6C8AF1CC72E1C6E6FBC4,FAEA36DABA0E46CD081A7FA49DAD8FE0,A9EF1048419D8E2D4848D9389275CC0E,СОЕДИНЕННОЕ КОРОЛЕВСТВО,100
342733,5EEBF058F0AADCB4095A39E8EED63CF3,3B5BEA39AF78664AEA44752371845804,1056EF3A7F6831AFF867A3C072328983,B8AF2335E04E7BAD5168D9B39FABAC21,6D2580183CEF6C8AF1CC72E1C6E6FBC4,FAEA36DABA0E46CD081A7FA49DAD8FE0,A9EF1048419D8E2D4848D9389275CC0E,СОЕДИНЕННОЕ КОРОЛЕВСТВО,100
342734,B54380CC5CCC0F3DDD2D448177ECB4BC,3B5BEA39AF78664AEA44752371845804,B84184EE78EB828BAE9C6C0324C0CBA6,B8AF2335E04E7BAD5168D9B39FABAC21,6D2580183CEF6C8AF1CC72E1C6E6FBC4,FAEA36DABA0E46CD081A7FA49DAD8FE0,35DE9DA6A73429012DCB8B879A24E731,ФРАНЦИЯ,75
342735,C5B0FEC1CDD8A55C3B40B8289BDCFD9E,3B5BEA39AF78664AEA44752371845804,99B46FBA9D2569F172625204EA75D7ED,2868B842B46F754C088D89E130F89585,6D2580183CEF6C8AF1CC72E1C6E6FBC4,58A4B52373651DA4292AD5725D388F8A,7AE0EEE7742C41B6D00373FC7F1D3B43,ФРАНЦИЯ,6

In [33]:
# df.drop_duplicates(subset=["gtin"], keep='last', inplace=True)

ids = df["gtin"]
df[ids.isin(ids[ids.duplicated()])].sort_values("gtin")

Empty DataFrame
Columns: [gtin, inn, product_name, product_short_name, tnved, tnved10, brand, country, volume]
Index: []